// OptimaScript-specific Visual Studio Code inspired themes extracted from the
// upstream highlight.js palettes to provide familiar colours without pulling
// flutter_highlight in at runtime.
import 'package:flutter/painting.dart';

const vsCodeLightTheme = <String, TextStyle>{
  'root': TextStyle(
    color: Color(0xff1f1f1f),
    backgroundColor: Color(0xffffffff),
  ),
  'keyword': TextStyle(color: Color(0xff0000ff), fontWeight: FontWeight.w600),
  'literal': TextStyle(color: Color(0xff0000ff)),
  'symbol': TextStyle(color: Color(0xff00b0e8)),
  'built_in': TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.w600),
  'builtin-name':
      TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.w600),
  'type': TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.w600),
  'class': TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.w600),
  'title': TextStyle(color: Color(0xff795e26), fontWeight: FontWeight.w600),
  'function': TextStyle(color: Color(0xff795e26)),
  'params': TextStyle(color: Color(0xff1f1f1f)),
  'number': TextStyle(color: Color(0xff098658)),
  'string': TextStyle(color: Color(0xffa31515)),
  'meta-string': TextStyle(color: Color(0xffa31515)),
  'regexp': TextStyle(color: Color(0xff2b91af)),
  'variable': TextStyle(color: Color(0xff001080)),
  'template-variable': TextStyle(color: Color(0xff001080)),
  'attribute': TextStyle(color: Color(0xff795e26)),
  'attr': TextStyle(color: Color(0xff795e26)),
  'tag': TextStyle(color: Color(0xff800000)),
  'selector-tag': TextStyle(color: Color(0xff800000)),
  'selector-id': TextStyle(color: Color(0xff800000)),
  'selector-class': TextStyle(color: Color(0xff800000)),
  'selector-attr': TextStyle(color: Color(0xff800000)),
  'selector-pseudo': TextStyle(color: Color(0xff800000)),
  'meta': TextStyle(color: Color(0xff2b91af)),
  'meta-keyword': TextStyle(color: Color(0xff2b91af)),
  'doctag': TextStyle(color: Color(0xff808080)),
  'comment': TextStyle(color: Color(0xff008000), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff008000), fontStyle: FontStyle.italic),
  'operator': TextStyle(color: Color(0xff0000ff)),
  'punctuation': TextStyle(color: Color(0xff1f1f1f)),
  'bullet': TextStyle(color: Color(0xff00b0e8)),
  'addition': TextStyle(backgroundColor: Color(0xffe8f5ff)),
  'deletion': TextStyle(backgroundColor: Color(0xffffebeb)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};

const vsCodeDarkTheme = <String, TextStyle>{
  'root': TextStyle(
    color: Color(0xffd4d4d4),
    backgroundColor: Color(0xff1e1e1e),
  ),
  'keyword': TextStyle(color: Color(0xff569cd6)),
  'literal': TextStyle(color: Color(0xff569cd6)),
  'symbol': TextStyle(color: Color(0xff569cd6)),
  'built_in': TextStyle(color: Color(0xff4ec9b0)),
  'builtin-name': TextStyle(color: Color(0xff4ec9b0)),
  'type': TextStyle(color: Color(0xff4ec9b0)),
  'class': TextStyle(color: Color(0xff4ec9b0)),
  'function': TextStyle(color: Color(0xffdcdcaa)),
  'title': TextStyle(color: Color(0xffdcdcaa)),
  'params': TextStyle(color: Color(0xff9cdcfe)),
  'variable': TextStyle(color: Color(0xff9cdcfe)),
  'template-variable': TextStyle(color: Color(0xffc586c0)),
  'number': TextStyle(color: Color(0xffb5cea8)),
  'string': TextStyle(color: Color(0xffce9178)),
  'meta-string': TextStyle(color: Color(0xffce9178)),
  'regexp': TextStyle(color: Color(0xffd16969)),
  'attribute': TextStyle(color: Color(0xff9cdcfe)),
  'attr': TextStyle(color: Color(0xff9cdcfe)),
  'tag': TextStyle(color: Color(0xff9b9b9b)),
  'selector-tag': TextStyle(color: Color(0xffd7ba7d)),
  'selector-id': TextStyle(color: Color(0xffd7ba7d)),
  'selector-class': TextStyle(color: Color(0xffd7ba7d)),
  'selector-attr': TextStyle(color: Color(0xffd7ba7d)),
  'selector-pseudo': TextStyle(color: Color(0xffd7ba7d)),
  'meta': TextStyle(color: Color(0xff9b9b9b)),
  'meta-keyword': TextStyle(color: Color(0xff9b9b9b)),
  'doctag': TextStyle(color: Color(0xff608b4e)),
  'comment': TextStyle(color: Color(0xff6a9955), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff6a9955), fontStyle: FontStyle.italic),
  'operator': TextStyle(color: Color(0xffd4d4d4)),
  'punctuation': TextStyle(color: Color(0xffd4d4d4)),
  'bullet': TextStyle(color: Color(0xffd7ba7d)),
  'addition': TextStyle(backgroundColor: Color(0xff144212)),
  'deletion': TextStyle(backgroundColor: Color(0xff601010)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
