// Adapted from flutter_highlight theme definitions to avoid depending on
// the unmaintained package imports.
import 'package:flutter/painting.dart';

const vscodeLightTheme = <String, TextStyle>{
  'root': TextStyle(
    color: Color(0xff1f1f1f),
    backgroundColor: Color(0xffffffff),
  ),
  'comment': TextStyle(color: Color(0xff008000)),
  'quote': TextStyle(color: Color(0xff008000)),
  'keyword': TextStyle(color: Color(0xff0000ff)),
  'selector-tag': TextStyle(color: Color(0xff0000ff)),
  'literal': TextStyle(color: Color(0xff0000ff)),
  'number': TextStyle(color: Color(0xff098658)),
  'regexp': TextStyle(color: Color(0xff811f3f)),
  'string': TextStyle(color: Color(0xffa31515)),
  'doctag': TextStyle(color: Color(0xffa31515)),
  'title': TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.bold),
  'title.class': TextStyle(color: Color(0xff267f99), fontWeight: FontWeight.bold),
  'title.function': TextStyle(color: Color(0xff795e26), fontWeight: FontWeight.w600),
  'type': TextStyle(color: Color(0xff267f99)),
  'built_in': TextStyle(color: Color(0xff795e26)),
  'builtin-name': TextStyle(color: Color(0xff795e26)),
  'attribute': TextStyle(color: Color(0xff001080)),
  'attr': TextStyle(color: Color(0xff001080)),
  'property': TextStyle(color: Color(0xff001080)),
  'variable': TextStyle(color: Color(0xff001080)),
  'template-variable': TextStyle(color: Color(0xff001080)),
  'symbol': TextStyle(color: Color(0xffaf00db)),
  'params': TextStyle(color: Color(0xff267f99)),
  'meta': TextStyle(color: Color(0xff795e26)),
  'meta-string': TextStyle(color: Color(0xffa31515)),
  'link': TextStyle(color: Color(0xff267f99)),
  'bullet': TextStyle(color: Color(0xff795e26)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};

const vscodeDarkTheme = <String, TextStyle>{
  'root': TextStyle(
    color: Color(0xffd4d4d4),
    backgroundColor: Color(0xff1e1e1e),
  ),
  'comment': TextStyle(color: Color(0xff6a9955)),
  'quote': TextStyle(color: Color(0xff6a9955)),
  'keyword': TextStyle(color: Color(0xffc586c0)),
  'selector-tag': TextStyle(color: Color(0xffc586c0)),
  'literal': TextStyle(color: Color(0xff569cd6)),
  'number': TextStyle(color: Color(0xffb5cea8)),
  'regexp': TextStyle(color: Color(0xffd16969)),
  'string': TextStyle(color: Color(0xffce9178)),
  'doctag': TextStyle(color: Color(0xffce9178)),
  'title': TextStyle(color: Color(0xff4ec9b0), fontWeight: FontWeight.bold),
  'title.class': TextStyle(color: Color(0xff4ec9b0), fontWeight: FontWeight.bold),
  'title.function': TextStyle(color: Color(0xffdcdcaa), fontWeight: FontWeight.w600),
  'type': TextStyle(color: Color(0xff4ec9b0)),
  'built_in': TextStyle(color: Color(0xffdcdcaa)),
  'builtin-name': TextStyle(color: Color(0xffdcdcaa)),
  'attribute': TextStyle(color: Color(0xff9cdcfe)),
  'attr': TextStyle(color: Color(0xff9cdcfe)),
  'property': TextStyle(color: Color(0xff9cdcfe)),
  'variable': TextStyle(color: Color(0xff9cdcfe)),
  'template-variable': TextStyle(color: Color(0xff9cdcfe)),
  'symbol': TextStyle(color: Color(0xff569cd6)),
  'params': TextStyle(color: Color(0xff9cdcfe)),
  'meta': TextStyle(color: Color(0xff9cdcfe)),
  'meta-string': TextStyle(color: Color(0xffce9178)),
  'link': TextStyle(color: Color(0xff569cd6)),
  'bullet': TextStyle(color: Color(0xffdcdcaa)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};

const githubTheme = <String, TextStyle>{
  'root': TextStyle(
    color: Color(0xff333333),
    backgroundColor: Color(0xfff8f8f8),
  ),
  'comment': TextStyle(color: Color(0xff999988), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff999988), fontStyle: FontStyle.italic),
  'keyword': TextStyle(color: Color(0xff333333), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xff333333), fontWeight: FontWeight.bold),
  'subst': TextStyle(color: Color(0xff333333), fontWeight: FontWeight.normal),
  'number': TextStyle(color: Color(0xff008080)),
  'literal': TextStyle(color: Color(0xff008080)),
  'variable': TextStyle(color: Color(0xff008080)),
  'template-variable': TextStyle(color: Color(0xff008080)),
  'string': TextStyle(color: Color(0xffdd1144)),
  'doctag': TextStyle(color: Color(0xffdd1144)),
  'title': TextStyle(color: Color(0xff990000), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff990000), fontWeight: FontWeight.bold),
  'selector-id':
      TextStyle(color: Color(0xff990000), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff445588), fontWeight: FontWeight.bold),
  'tag': TextStyle(color: Color(0xff000080), fontWeight: FontWeight.normal),
  'name': TextStyle(color: Color(0xff000080), fontWeight: FontWeight.normal),
  'attribute':
      TextStyle(color: Color(0xff000080), fontWeight: FontWeight.normal),
  'regexp': TextStyle(color: Color(0xff009926)),
  'link': TextStyle(color: Color(0xff009926)),
  'symbol': TextStyle(color: Color(0xff990073)),
  'bullet': TextStyle(color: Color(0xff990073)),
  'built_in': TextStyle(color: Color(0xff0086b3)),
  'builtin-name': TextStyle(color: Color(0xff0086b3)),
  'meta': TextStyle(color: Color(0xff999999), fontWeight: FontWeight.bold),
  'deletion': TextStyle(backgroundColor: Color(0xffffdddd)),
  'addition': TextStyle(backgroundColor: Color(0xffddffdd)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};

const monokaiSublimeTheme = <String, TextStyle>{
  'root': TextStyle(
    backgroundColor: Color(0xff23241f),
    color: Color(0xfff8f8f2),
  ),
  'tag': TextStyle(color: Color(0xfff8f8f2)),
  'subst': TextStyle(color: Color(0xfff8f8f2)),
  'strong': TextStyle(color: Color(0xffa8a8a2), fontWeight: FontWeight.bold),
  'emphasis': TextStyle(color: Color(0xffa8a8a2), fontStyle: FontStyle.italic),
  'bullet': TextStyle(color: Color(0xffae81ff)),
  'quote': TextStyle(color: Color(0xffae81ff)),
  'number': TextStyle(color: Color(0xffae81ff)),
  'regexp': TextStyle(color: Color(0xffae81ff)),
  'literal': TextStyle(color: Color(0xffae81ff)),
  'link': TextStyle(color: Color(0xffae81ff)),
  'code': TextStyle(color: Color(0xffa6e22e)),
  'title': TextStyle(color: Color(0xffa6e22e)),
  'section': TextStyle(color: Color(0xffa6e22e)),
  'selector-class': TextStyle(color: Color(0xffa6e22e)),
  'keyword': TextStyle(color: Color(0xfff92672)),
  'selector-tag': TextStyle(color: Color(0xfff92672)),
  'name': TextStyle(color: Color(0xfff92672)),
  'attr': TextStyle(color: Color(0xfff92672)),
  'symbol': TextStyle(color: Color(0xff66d9ef)),
  'attribute': TextStyle(color: Color(0xff66d9ef)),
  'params': TextStyle(color: Color(0xfff8f8f2)),
  'string': TextStyle(color: Color(0xffe6db74)),
  'type': TextStyle(color: Color(0xffe6db74)),
  'built_in': TextStyle(color: Color(0xffe6db74)),
  'builtin-name': TextStyle(color: Color(0xffe6db74)),
  'selector-id': TextStyle(color: Color(0xffe6db74)),
  'selector-attr': TextStyle(color: Color(0xffe6db74)),
  'selector-pseudo': TextStyle(color: Color(0xffe6db74)),
  'addition': TextStyle(color: Color(0xffe6db74)),
  'variable': TextStyle(color: Color(0xffe6db74)),
  'template-variable': TextStyle(color: Color(0xffe6db74)),
  'comment': TextStyle(color: Color(0xff75715e)),
  'deletion': TextStyle(color: Color(0xff75715e)),
  'meta': TextStyle(color: Color(0xff75715e)),
};
