name: Global Script
scope: global
handlers:
  - event: workbook.open
    description: Message lors de l'ouverture du classeur
    actions:
      - log:
          message: "Classeur charge avec {{workbook.pageCount}} page(s)"
  - event: page.enter
    description: Notifie lorsque l'on change de page
    actions:
      - log:
          message: "Ouverture de {{page.name}}"
